#cloud-config
manage_etc_hosts: true
user: $CLOUD_INIT_USERNAME
password: $CLOUD_INIT_PASSWORD
chpasswd:
  expire: False
users:
  - name: $CLOUD_INIT_USERNAME
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - $CLOUD_INIT_PUBLIC_KEY
package_upgrade: true
packages:
  - bmon 
  - bwm-ng 
  - curl
  - cloud-utils
  - cloud-guest-utils
  - git
  - htop 
  - iftop 
  - iotop 
  - libpam-systemd 
  - locales-all 
  - locate 
  - make
  - nano 
  - net-tools 
  - ntpdate 
  - qemu-guest-agent 
  - rsync 
  - strace 
  - sysstat 
  - sudo 
  - tcpdump 
  - tmux 
  - zsh 
  - zsh-autosuggestions 
  - zsh-syntax-highlighting
runcmd:
  - snap remove lxd
  - snap remove core18
  - snap remove snapd
  - apt purge snapd -y
  - apt autoremove -y
  - apt autoclean -y
  - cloud-init clean 
  - history -c
  - history -w
  - fstrim -av
  - systemctl start qemu-guest-agent
