#cloud-config
manage_etc_hosts: false
user: $CLOUD_INIT_USERNAME
password: $CLOUD_INIT_PASSWORD
chpasswd:
  expire: False
users:
  - name: $CLOUD_INIT_USERNAME
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - $CLOUD_INIT_PUBLIC_KEY
package_update: true
package_upgrade: true
packages:
  - bmon 
  - bwm-ng 
  - curl
  - cloud-utils
  - cloud-guest-utils
  - git
  - htop 
  - iftop 
  - iotop 
  - libpam-systemd 
  - locales-all 
  - locate 
  - make
  - nano 
  - net-tools 
  - ntpsec 
  - qemu-guest-agent 
  - rsync 
  - strace 
  - sysstat 
  - sudo 
  - tcpdump 
  - tmux 
  - zsh 
  - zsh-autosuggestions 
  - zsh-syntax-highlighting
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - snap remove lxd
  - snap remove core18
  - snap remove snapd
  - apt purge snapd -y
  - apt autoremove -y
  - apt autoclean -y
  - history -c
  - history -w
  - fstrim -av

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp-identifier: mac

