#cloud-config
manage_etc_hosts: true
# user: $CLOUD_INIT_USERNAME
# password: $CLOUD_INIT_PASSWORD
ssh_pwauth: false
ssh_deletekeys: true
ssh_genkeytypes: [rsa, ed25519]
disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
allow_public_ssh_keys: true
ssh_quiet_keygen: true
ssh_publish_hostkeys:
  enabled: true
  blacklist: [dsa]
chpasswd:
  expire: false
users:
  - name: $CLOUD_INIT_USERNAME
    plain_text_passwd: $CLOUD_INIT_PASSWORD
    groups: [adm, sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - $CLOUD_INIT_PUBLIC_KEY
packages: 
  - curl
  - cloud-utils
  - cloud-guest-utils
  - git
  - htop 
  - libpam-systemd
  - make
  - nano
  - net-tools
  - ntpsec
  - qemu-guest-agent
  - rsync
  - strace
  - sysstat
  - sudo
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
runcmd:
  - systemctl start qemu-guest-agent
  - snap remove $(snap list | grep -v snapd | awk '!/^Name|^core/ {print $1}')
  - snap remove snapd
  - apt purge snapd -y
  - apt autoremove -y
  - apt autoclean -y
  - apt update
  - apt full-upgrade -y
  - systemctl daemon-reload
  - echo -n > /etc/machine-id 
  - rm /var/lib/dbus/machine-id
  - ln -s /etc/machine-id  /var/lib/dbus/machine-id
  - fstrim -av
  
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp-identifier: mac
