#cloud-config
manage_etc_hosts: true
timezone: ${VM_TIMEZONE}
chpasswd:
  expire: false
users:
  - name: $CLOUD_INIT_USERNAME
    plain_text_passwd: $CLOUD_INIT_PASSWORD
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - $CLOUD_INIT_PUBLIC_KEY
apt:
  conf: |
    APT {
        Get {
            Assume-Yes 'true';
            Fix-Broken 'true';
        }
    }
    Acquire {
      Check-Date "false";
      Check-Valid-Until "false";
      Max-FutureTime "86400";
    }
package_update: true
package_upgrade: true
package_reboot_if_required: false
packages:
  - curl
  - git
  - htop 
  - libpam-systemd
  - make
  - nano
  - net-tools
  - qemu-guest-agent
  - rsync
  - strace
  - sysstat
  - sudo
  - unattended-upgrades
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
runcmd:
  - systemctl start qemu-guest-agent
  - snap remove $(snap list | grep -v snapd | awk '!/^Name|^core/ {print $1}')
  - snap remove snapd
  - apt-get purge snapd -y
  - apt-get autoremove -y
  - apt-get autoclean -y
  - touch ~/.sudo_as_admin_successful
  - echo -n > /etc/machine-id 
  - rm /var/lib/dbus/machine-id
  - ln -s /etc/machine-id  /var/lib/dbus/machine-id
  - fstrim -av

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp-identifier: mac
