#cloud-config
manage_etc_hosts: true
timezone: ${VM_TIMEZONE}
chpasswd:
  expire: false
users:
  - name: $CLOUD_INIT_USERNAME
    plain_text_passwd: $CLOUD_INIT_PASSWORD
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - $CLOUD_INIT_PUBLIC_KEY
# apt:
#   primary:
#     - arches: 
#       - default
#       - amd64
#       search_dns: True
# package_update: true
# package_upgrade: true
# package_reboot_if_required: false
packages:
  - curl
  - git
  - htop 
  - libpam-systemd
  - make
  - nano
  - net-tools
  - rsync
  - strace
  - sysstat
  - sudo
  - unattended-upgrades
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
runcmd:
  # - apt-get install qemu-guest-agent -y
  # - systemctl start qemu-guest-agent
  - snap remove $(snap list | grep -v snapd | awk '!/^Name|^core/ {print $1}')
  - snap remove snapd
  - apt-get purge snapd -y
  - apt-get autoremove -y
  - apt-get autoclean -y
  - touch ~/.sudo_as_admin_successful
  - echo -n > /etc/machine-id 
  - rm /var/lib/dbus/machine-id
  - ln -s /etc/machine-id  /var/lib/dbus/machine-id
  - fstrim -av

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp-identifier: mac
