#cloud-config
manage_etc_hosts: true
user: $CLOUD_INIT_USERNAME
password: $CLOUD_INIT_PASSWORD
# ssh_pwauth: false
# ssh_deletekeys: true
# ssh_genkeytypes: [rsa, ed25519]
# disable_root: true
# disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
# allow_public_ssh_keys: true
ssh_quiet_keygen: true
# ssh_publish_hostkeys:
#   enabled: true
#   blacklist: [dsa]
chpasswd:
  expire: false
users:
  - name: $CLOUD_INIT_USERNAME
    # passwd: $CLOUD_INIT_PASSWORD
    # plain_text_passwd: $CLOUD_INIT_PASSWORD
    # groups: [adm, sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - $CLOUD_INIT_PUBLIC_KEY
apt:
  primary:
    - arches: [default]
      search_dns: True
package_update: true
package_upgrade: true
package_reboot_if_required: false
packages: 
  - curl
  - cloud-utils
  - cloud-guest-utils
  - git
  - htop 
  - libpam-systemd
  - make
  - nano
  - net-tools
  - ntpsec
  - qemu-guest-agent
  - rsync
  - strace
  - sysstat
  - sudo
  - unattended-upgrades
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
runcmd:
  - systemctl start qemu-guest-agent
  - snap remove $(snap list | grep -v snapd | awk '!/^Name|^core/ {print $1}')
  - snap remove snapd
  - apt-get purge snapd -y
  - apt-get autoremove -y
  - apt-get autoclean -y
  - systemctl mask apt-news.service
  - systemctl mask esm-cache.service
  - mv /etc/apt/apt.conf.d/20apt-esm-hook.conf /etc/apt/apt.conf.d/20apt-esm-hook.conf.disabled
  - rm /etc/update-motd.d/88-esm-announce 
  - rm /var/lib/ubuntu-advantage/messages/motd-esm-announce
  - systemctl daemon-reload
  - echo -n > /etc/machine-id 
  - rm /var/lib/dbus/machine-id
  - ln -s /etc/machine-id  /var/lib/dbus/machine-id
  - fstrim -av

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp-identifier: mac
